In [1]:
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [3]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x+y)

[3. 6. 9.]


In [5]:
print(x*y)
x/y

[ 2.  8. 18.]


array([0.5, 0.5, 0.5])

In [7]:
A = np.array([[1, 2], [3, 4]])
print(A)
A.shape

[[1 2]
 [3 4]]


(2, 2)

In [17]:
B = np.array([[3, 0, 1], [0, 6, 2]])
[10, 1, 2]*B
B.shape

(2, 3)

In [22]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X[2][0])

0


In [24]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [27]:
X = X.flatten()
X

array([51, 55, 14, 19,  0,  4])

In [34]:
X>15
X[X>15]

array([51, 55, 19])

# matplotlib

In [1]:
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 6, 0.1) # 0에서 6까지 0.1 간격으로 생성
y = np.sin(x)

plt.plot(x, y)
plt.show()

In [11]:
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 6, 0.1)
y1 = np.sin(x)
y2 = np.cos(x)

plt.plot(x, y1, label="sin")
plt.plot(x, y2, label="cos", linestyle="--")
plt.xlabel("x")
plt.ylabel("y")
plt.title('sin & cos')
plt.legend()  # 각 라인이 무엇을 의미하는지 나타낸다. 
plt.show()