## Neural Network

In [10]:
import numpy as np
import matplotlib.pyplot as plt

def step_function(x):
    return np.array(x>0, dtype=np.int)


In [11]:
step_function(np.array([1, -2, 3, -4]))

array([1, 0, 1, 0])

In [14]:
x = np.arange(-5.0, 5.0, 0.1)
y = step_function(x)
plt.plot(x, y)
plt.ylim(-0.1, 1.1)
plt.show()

In [21]:
def sigmoid(x):
    return 1/(1+ np.exp(-x))

In [18]:
x = np.array([-1.0, 1.0, 2.0])
sigmoid(x)

array([0.26894142, 0.73105858, 0.88079708])

In [20]:
x = np.arange(-5.0, 5.0, 0.1)
y = sigmoid(x)
plt.plot(x, y)
plt.ylim(-0.1, 1.1)
plt.show()

## relu

In [22]:
def relu(x):
    return np.maximum(0, x)

In [23]:
relu(np.array([1.2, 3.3, 4.56, 34.2]))

array([ 1.2 ,  3.3 ,  4.56, 34.2 ])

## 3.3 다차원 배열

In [26]:
import numpy as np
A = np.array([1, 2, 3, 4])
print(A)
print(A.shape)
print(A.shape[0])
print(np.ndim(A)) #배열의 차원 수 

[1 2 3 4]
(4,)
4
1


In [27]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)
np.ndim(B)


[[1 2]
 [3 4]
 [5 6]]


2

In [31]:
A = np.array([[1, 2], [3, 4]])
A.shape
B = np.array([[5, 6], [7, 8]])
B.shape
A.dot(B)

array([[19, 22],
       [43, 50]])

In [32]:
X = np.array([1, 2])
X.shape 

W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)

W.shape 

Y = np.dot(X, W)
print(Y)

[[1 3 5]
 [2 4 6]]
[ 5 11 17]


In [34]:
X = np.array([1, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1

(2, 3)
(2,)
(3,)


In [36]:
Z1 = sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [38]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

(3,)
(3, 2)
(2,)


In [39]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = A3

In [41]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['B1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['B2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['B3'] = np.array([0.1, 0.2])

    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    B1, B2, B3 = network['B1'], network['B2'], network['B3']

    a1 = np.dot(x, W1) + B1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + B2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + B3
    y = a3

    return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)


[0.31682708 0.69627909]


In [44]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a/sum_exp_a
    
    return y

In [45]:
softmax([0.3, 2.9, 4.0])

array([0.01821127, 0.24519181, 0.73659691])

In [54]:
from keras.datasets import mnist

(X_train, Y_train) , (X_test, Y_test) = mnist.load_data()
X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)

In [55]:
print(X_test.shape)

(10000, 784)
